<?php
/**
 * EmbeddedFlowApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  belenka\Everifin\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Everifin PayGate
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace belenka\Everifin\Client\Test\Api;

use \belenka\Everifin\Client\Configuration;
use \belenka\Everifin\Client\ApiException;
use \belenka\Everifin\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmbeddedFlowApiTest Class Doc Comment
 *
 * @category Class
 * @package  belenka\Everifin\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmbeddedFlowApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for initPayment
     *
     * Init Payment.
     *
     */
    public function testInitPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processPayment
     *
     * Process Payment.
     *
     */
    public function testProcessPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
